version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: simple-sfa-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sfa
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sfa-network

  php:
    build: ./php
    container_name: simple-sfa-php
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html
    depends_on:
      - db
    networks:
      - sfa-network

networks:
  sfa-network:
    driver: bridge
